export const CARGAR_USUARIO = 'CARGAR_USUARIO'
export const LOGOUT = 'LOGOUT'
export const MOSTRAR_NOTIFICACION = 'MOSTRAR_NOTIFICACION'
export const MOSTRAR_LOADER = 'MOSTRAR_LOADER'
export const ACTIVAR_OSCURO = "ACTIVAR_OSCURO"
